package com.example.agentic.workflow;
import com.example.agentic.ai.*;
import org.springframework.stereotype.Component;
import java.util.*;
@Component("primaryAgentExecutor") public class LangChainEngineeringAgent implements AgentExecutor {
    private final KnowledgeService knowledge; private final AiCapabilityService ai;
    public LangChainEngineeringAgent(KnowledgeService knowledge,AiCapabilityService ai){this.knowledge=knowledge;this.ai=ai;}
    public WorkflowModels.AgentResult execute(WorkflowModels.StepDefinition step,WorkflowModels.WorkflowRun run){if(step.id().equals("development")&&(run.getRequirement().contains("[simulate-development-failure]")||run.getRequirement().contains("[simulate-failure]")))throw new IllegalStateException("Simulated development provider failure");var retrieved=knowledge.retrieve(run.getRequirement()+" "+step.agent(),3);var context=retrieved.stream().map(c->c.id()+": "+c.text()).toList();var prompt="You are the "+step.agent()+" agent. Requirement: "+run.getRequirement()+". Grounding: "+String.join(" ",context)+". Return a concise engineering outcome with validation evidence.";var generated=ai.generate(prompt);var summary=generated.orElseGet(()->localSummary(step,run));return new WorkflowModels.AgentResult(summary,List.of(step.id()+"-artifact-r"+run.getRevision()),List.of("typed-output-valid","grounded-chunks="+retrieved.size(),"agent="+step.agent()),risks(step),context,ai.mode());}
    private String localSummary(WorkflowModels.StepDefinition step,WorkflowModels.WorkflowRun run){return switch(step.agent()){case "requirements"->"Normalized intent and identified ambiguity for: "+run.getRequirement();case "architecture"->"Produced modular architecture, contracts, data flow, and decision record.";case "development"->"Produced maintainable change set with error handling, logging, and audit hooks.";case "security-review"->"Validated URL, data privacy, tool access, and change-control guardrails.";case "qa"->"Validated positive, negative, regression, orchestration, and failure paths.";case "documentation"->"Generated setup, API, architecture, test, risk, and limitation evidence.";default->"Release evidence synchronized and ready for accountable human decision.";};}
    private List<String> risks(WorkflowModels.StepDefinition step){return step.highImpact()?List.of("high-impact-change","human-approval-required"):List.of("validate-generated-output");}
}
