package com.example.agentic.workflow;
import com.example.agentic.audit.AuditService;
import com.example.agentic.common.DomainException;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import static com.example.agentic.workflow.WorkflowModels.*;
@Service public class WorkflowOrchestrator {
    private final WorkflowGraphProvider graphs; private final WorkflowStore store; private final AgentExecutor primary; private final AgentExecutor fallback; private final GuardrailPolicy guardrails; private final AuditService audit; private final ExecutorService pool=Executors.newVirtualThreadPerTaskExecutor();
    public WorkflowOrchestrator(WorkflowGraphProvider graphs,WorkflowStore store,@Qualifier("primaryAgentExecutor") AgentExecutor primary,@Qualifier("fallbackAgentExecutor") AgentExecutor fallback,GuardrailPolicy guardrails,AuditService audit){this.graphs=graphs;this.store=store;this.primary=primary;this.fallback=fallback;this.guardrails=guardrails;this.audit=audit;}
    public synchronized WorkflowRun start(String scenario,String requirement,String actor,String correlation){var run=new WorkflowRun();run.setScenario(scenario);run.setRequirement(requirement);run.setGraph(graphs.graphFor(scenario));run.getGraph().keySet().forEach(id->run.getSteps().put(id,new StepState(id)));decision(run,"run.created",run.getId().toString(),"scenario="+scenario,actor);store.save(run);audit.record(actor,"workflow.start",run.getId().toString(),"success",correlation,"scenario="+scenario);return run;}
    public WorkflowRun get(UUID id){return store.find(id).orElseThrow(()->new DomainException("run_not_found","Workflow run was not found",HttpStatus.NOT_FOUND));}
    public synchronized WorkflowRun advance(UUID id,String actor,String correlation){var run=get(id);if(Set.of(RunStatus.SUCCEEDED,RunStatus.ROLLED_BACK,RunStatus.SAFE_STOPPED).contains(run.getStatus()))return run;run.setStatus(RunStatus.RUNNING);while(true){var ready=run.getGraph().values().stream().filter(s->run.getSteps().get(s.id()).getStatus()==StepStatus.PENDING&&s.dependsOn().stream().allMatch(d->run.getSteps().get(d).getStatus()==StepStatus.SUCCEEDED)).toList();if(ready.isEmpty())break;var executable=new ArrayList<StepDefinition>();for(var step:ready){if(step.requiresApproval()&&!run.getApprovals().contains(step.id()))run.getSteps().get(step.id()).setStatus(StepStatus.AWAITING_APPROVAL);else executable.add(step);}if(executable.isEmpty()){run.setStatus(RunStatus.AWAITING_APPROVAL);break;}var futures=executable.stream().map(step->CompletableFuture.runAsync(()->execute(run,step,actor,correlation),pool)).toArray(CompletableFuture[]::new);CompletableFuture.allOf(futures).join();if(run.getSteps().values().stream().anyMatch(s->s.getStatus()==StepStatus.FAILED)){run.setStatus(RunStatus.SAFE_STOPPED);run.setCompletedAt(Instant.now());break;}}if(run.getSteps().values().stream().allMatch(s->s.getStatus()==StepStatus.SUCCEEDED)){run.setStatus(RunStatus.SUCCEEDED);run.setCompletedAt(Instant.now());if(run.getLastFailureAt()!=null)run.setRecoveredAt(Instant.now());}store.save(run);return run;}
    public synchronized WorkflowRun approve(UUID id,String stepId,String actor,String reason,String correlation){var run=get(id);var state=run.getSteps().get(stepId);if(state==null||state.getStatus()!=StepStatus.AWAITING_APPROVAL)throw new DomainException("invalid_approval","Step is not awaiting approval",HttpStatus.CONFLICT);run.getApprovals().add(stepId);state.setStatus(StepStatus.PENDING);decision(run,"approval.granted",stepId,reason,actor);store.save(run);audit.record(actor,"workflow.approve",id+"/"+stepId,"success",correlation,reason);return run;}
    public synchronized WorkflowRun replan(UUID id,String requirement,String actor,String correlation){var run=get(id);run.setRequirement(requirement);run.setRevision(run.getRevision()+1);run.getSteps().replaceAll((key,value)->new StepState(key));run.getApprovals().clear();run.setStatus(RunStatus.PENDING);run.setCompletedAt(null);decision(run,"run.replanned",id.toString(),"upstream requirement changed; downstream artifacts invalidated",actor);store.save(run);audit.record(actor,"workflow.replan",id.toString(),"success",correlation,"revision="+run.getRevision());return run;}
    public synchronized WorkflowRun rollback(UUID id,String actor,String reason,String correlation){var run=get(id);run.getSteps().values().stream().filter(s->s.getStatus()==StepStatus.SUCCEEDED).forEach(s->s.setStatus(StepStatus.ROLLED_BACK));run.setStatus(RunStatus.ROLLED_BACK);run.setCompletedAt(Instant.now());decision(run,"run.rollback",id.toString(),reason,actor);store.save(run);audit.record(actor,"workflow.rollback",id.toString(),"success",correlation,reason);return run;}
    public List<WorkflowRun> all(){return store.all();}
    private void execute(WorkflowRun run,StepDefinition step,String actor,String correlation){var state=run.getSteps().get(step.id());guardrails.validateEntry(run,step,actor);Exception failure=null;for(int attempt=1;attempt<=step.maxAttempts();attempt++){state.setStatus(StepStatus.RUNNING);state.setAttempts(attempt);try{var result=primary.execute(step,run);guardrails.validateExit(step,result);state.setResult(result);state.setStatus(StepStatus.SUCCEEDED);decision(run,"step.succeeded",step.id(),"attempt="+attempt,step.agent());return;}catch(Exception ex){failure=ex;decision(run,"step.retry",step.id(),ex.getMessage(),step.agent());}}try{var result=fallback.execute(step,run);guardrails.validateExit(step,result);state.setFallbackUsed(true);state.setResult(result);state.setStatus(StepStatus.SUCCEEDED);decision(run,"step.fallback",step.id(),"primary exhausted",step.agent());}catch(Exception ex){state.setStatus(StepStatus.FAILED);state.setError(failure==null?ex.getMessage():failure.getMessage());run.setLastFailureAt(Instant.now());audit.record(actor,"workflow.step",run.getId()+"/"+step.id(),"failed",correlation,state.getError());}}
    private void decision(WorkflowRun run,String kind,String subject,String reason,String actor){synchronized(run.getDecisions()){run.getDecisions().add(new Decision(Instant.now(),kind,subject,reason,actor));}}
}
